/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockticker;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel; 
import javax.swing.Timer;

/**
 *
 * @author asotis
 */
public class StockTicker extends javax.swing.JFrame {

    /**
     * Creates new form StockTicker2
     */
    public StockTicker() {
        
        
        initComponents();
        initialize();
       
        
        Timer timer = new Timer(20, new ActionListener() {
            
        @Override
            public void actionPerformed(ActionEvent e) {
                update();      
            }
        });
        timer.start();
        
        }
    
    private void addTicker(String theTicker) throws IOException{
        
        listModel.addElement(theTicker);
        
        String thePrice = stockPricer.getPrice(theTicker);
        jTxtDisplay.setText(jTxtDisplay.getText() + "   "+theTicker + ":  " + thePrice);
        
        
        jLabScroll.setText(jTxtDisplay.getText());
    }
    
    private void initialize(){
        
        jTxtDisplay.setEditable(false);
        
        // I'm pretty sure this is doing nothing
        //jScrollPane2.setBounds(jScrollPane2.getX(), jScrollPane2.getY(), jScrollPane2.getWidth()*2, jScrollPane2.getHeight());
    
    }
    
    private void update(){
        
        jTxtDisplay.setLocation(jTxtDisplay.getX()-SCROLLSPEED, jTxtDisplay.getY());
        if(jTxtDisplay.getX() < -jTxtDisplay.getWidth()){
            jTxtDisplay.setLocation(jTxtDisplay.getWidth(),jTxtDisplay.getY());
        }
        
        jLabScroll.setLocation(jLabScroll.getX()-SCROLLSPEED, jLabScroll.getY());
        if(jLabScroll.getX() < -jLabScroll.getWidth()){
            jLabScroll.setLocation(getContentPane().getWidth() ,jLabScroll.getY());
        }
        
        
        
        
        /* // adding prices to second text box
        ListModel model = jList1.getModel();
        
        String[] strings2 = new String[model.getSize()];
        for (int i=0; i<model.getSize(); i++){
            try {
                strings2[i] = stockPricer.getPrice((String)(model.getElementAt(i)));
            } catch (IOException ex) {
                Logger.getLogger(StockTicker.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = strings2;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUserTxtEntry = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtDisplay = new javax.swing.JTextPane();
        jLabUserPrompt = new javax.swing.JLabel();
        jLabScroll = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jUserTxtEntry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jUserTxtEntry.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jUserTxtEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserTxtEntryActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTxtDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(jTxtDisplay);

        jLabUserPrompt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabUserPrompt.setText("Enter Stock Ticker:  ");
        jLabUserPrompt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(217, 959, Short.MAX_VALUE)
                .addComponent(jLabUserPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUserTxtEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabUserPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserTxtEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserTxtEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserTxtEntryActionPerformed
        try {
            print(evt.getActionCommand());
            addTicker(evt.getActionCommand());
            jUserTxtEntry.setText("");
        } catch (IOException ex) {
            Logger.getLogger(StockTicker.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jUserTxtEntryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockTicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockTicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockTicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockTicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockTicker().setVisible(true);
                
            }
        });
    }
    
    	private static void print(Object message){		
		System.out.println(message);
	}// End print

    private final int SCROLLSPEED = 3;
    private final StockPricer stockPricer = new StockPricer();
    private DefaultListModel listModel = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabScroll;
    private javax.swing.JLabel jLabUserPrompt;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTxtDisplay;
    private javax.swing.JTextField jUserTxtEntry;
    // End of variables declaration//GEN-END:variables
}
