/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockticker;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel; 

/**
 *
 * @author asotis
 */
public class StockTicker extends javax.swing.JFrame {

    /**
     * Creates new form StockTicker2
     */
    public StockTicker() {
        initComponents();
        initialize();
       
        
        }
    
    private void addTicker(String theTicker) throws IOException{
        
        listModel.addElement(theTicker);
        
        String thePrice = stockPricer.getPrice(theTicker);
        jTxtDisplay.setText(jTxtDisplay.getText() + "   "+theTicker + ":  " + thePrice);
    }
    
    private void initialize(){
        jList2.setModel(listModel);
    }
    
    private void update(){
        
        
        
        

        
        
        
        
        
        /* // adding prices to second text box
        ListModel model = jList1.getModel();
        
        String[] strings2 = new String[model.getSize()];
        for (int i=0; i<model.getSize(); i++){
            try {
                strings2[i] = stockPricer.getPrice((String)(model.getElementAt(i)));
            } catch (IOException ex) {
                Logger.getLogger(StockTicker.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = strings2;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jUserTxtEntry = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtDisplay = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList2);

        jUserTxtEntry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jUserTxtEntry.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jUserTxtEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserTxtEntryActionPerformed(evt);
            }
        });

        jTxtDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(jTxtDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addComponent(jUserTxtEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1)
                        .addGap(170, 170, 170))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jUserTxtEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserTxtEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserTxtEntryActionPerformed
        try {
            print(evt.getActionCommand());
            addTicker(evt.getActionCommand());
            jUserTxtEntry.setText("");
        } catch (IOException ex) {
            Logger.getLogger(StockTicker.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jUserTxtEntryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockTicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockTicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockTicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockTicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockTicker().setVisible(true);
                
            }
        });
    }
    
    	private static void print(Object message){		
		System.out.println(message);
	}// End print

    private StockPricer stockPricer = new StockPricer();
    DefaultListModel listModel = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTxtDisplay;
    private javax.swing.JTextField jUserTxtEntry;
    // End of variables declaration//GEN-END:variables
}
